name: Push on IPFS

on:
  push:
    branches:
      - release/**
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm ci
          npm run build
          touch dist/spa/.nojekyll

      - uses: actions/upload-artifact@v4
        with:
          name: aleph-swap
          path: dist/spa/
          overwrite: true

  push-to-ipfs:
    name: Push site to IPFS
    needs: build
    runs-on: ubuntu-22.04
    outputs:
      cid_v0: ${{ steps.push_to_ipfs.outputs.cid_v0 }}
      cid_v1: ${{ steps.push_to_ipfs.outputs.cid_v1 }}
    steps:
      - name: Download export artifact
        uses: actions/download-artifact@v4
        with:
          name: aleph-swap
          path: out

      - name: Push to IPFS
        id: push_to_ipfs
        uses: aleph-im/aleph-github-actions/push-to-ipfs@v1.3.1
        with:
          upload-dir: out